services:
  redis:
    image: redis:7-alpine
    container_name: valina-redis
    restart: unless-stopped


  web:
    image: valinta-apuri:latest
    container_name: valinta-web
    restart: unless-stopped
    depends_on:
      - redis

    environment:
      ENV: production
      TZ: Europe/Helsinki
      REDIS_HOST: redis

      TLS_CERT_FILE: /certs/cert.pem
      TLS_KEY_FILE: /certs/key.pem

    volumes:
      - ./certs:/certs:ro
      - img_data:/app/static/img_cur

    command: >
      gunicorn app:app
      --worker-class gthread
      --threads 4
      --workers 2
      --bind 0.0.0.0:8443
      --certfile ${TLS_CERT_FILE:-/certs/cert.pem}
      --keyfile ${TLS_KEY_FILE:-/certs/key.pem}
      --error-logfile -
      --http-protocols h2,h1

    ports:
      - "443:8443"

  bg:
    image: valinta-apuri:latest
    container_name: valinta-bg
    restart: unless-stopped

    depends_on:
      - redis

    environment:
      ENV: production
      TZ: Europe/Helsinki
      REDIS_HOST: redis

      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      TENANT_ID: ${TENANT_ID}
      DRIVE_ID: ${DRIVE_ID}

    volumes:
      - img_data:/app/static/img_cur

    command: python3.12 bg.py

  redirector:
    image: valinta-apuri:latest
    container_name: valinta-redirector
    restart: unless-stopped

    depends_on:
      - web

    command: python3.12 scripts/redirector.py

    ports:
      - "80:80"
  
volumes:
  img_data: