services:
  valinta-apuri:
    build: .
    ports:
      - "80:80"
      - "443:8443"
    environment:
      ENV: production
      TZ: Europe/Helsinki
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      TENANT_ID: ${TENANT_ID}
      DRIVE_ID: ${DRIVE_ID}
      TLS_CERT_FILE: /certs/cert.pem
      TLS_KEY_FILE: /certs/key.pem
    volumes:
      - ./certs:/certs:ro
    restart: unless-stopped